kind: ConfigMap
apiVersion: v1
metadata:
  name: backend  # Corrected name from bakend to backend
  namespace: expense
data:
  DB_HOST: mysql  # mysql component service name

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: expense
  name: backend
  labels:
    # deployment related labels
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    # pod definition
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for myservice; sleep 2; done;']
      containers:
      - name: backend
        image: chandureddy08/backend:v1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        envFrom:
          - configMapRef:
              name: backend  # Corrected name from bakend to backend

---

kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
