kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: expense
  name: mysql
  labels:
    # deployment related lables
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  template:
    # pod definition
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: chandureddy08/mysql:v1.0
---
kind: Service
apiVersion: v1 
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306